import { City } from '../../models/city';

export const CITIES: City[] = [
    { cityName: 'Reims', country: 'France' },
    { cityName: 'Münster', country: 'Germany' },
    { cityName: 'Rio de Janeiro', country: 'Brazil' },
    { cityName: 'Lyon', country: 'France' },
    { cityName: 'Charleroi', country: 'Belgium' },
    { cityName: 'Bern', country: 'Switzerland' },
    { cityName: 'Genève', country: 'Switzerland' },
    { cityName: 'Resende', country: 'Brazil' },
    { cityName: 'San Cristóbal', country: 'Venezuela' },
    { cityName: 'Graz', country: 'Austria' },
    { cityName: 'México D.F.', country: 'Mexico' },
    { cityName: 'Köln', country: 'Germany' },
    { cityName: 'Albuquerque', country: 'USA' },
    { cityName: 'Bräcke', country: 'Sweden' },
    { cityName: 'Strasbourg', country: 'France' },
    { cityName: 'Oulu', country: 'Finland' },
    { cityName: 'München', country: 'Germany' },
    { cityName: 'Caracas', country: 'Venezuela' },
    { cityName: 'Seattle', country: 'USA' },
    { cityName: 'Lander', country: 'USA' },
    { cityName: 'Cunewalde', country: 'Germany' },
    { cityName: 'Bergamo', country: 'Italy' },
    { cityName: 'Leipzig', country: 'Germany' },
    { cityName: 'Luleå', country: 'Sweden' },
    { cityName: 'Frankfurt a.M.', country: 'Germany' },
    { cityName: 'Madrid', country: 'Spain' },
    { cityName: 'Barquisimeto', country: 'Venezuela' },
    { cityName: 'Reggio Emilia', country: 'Italy' },
    { cityName: 'London', country: 'UK' },
    { cityName: 'Sao Paulo', country: 'Brazil' }
];
