language: node_js
sudo: true

cache:
  directories:
    - node
    - node_modules

dist: trusty

node_js:
  - 8.1.4

branches:
  only:
    - master
    - /^greenkeeper/.*$/

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_install:
  - npm install -g @angular/cli
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - npm run lint
  - npm run test -- --watch=false
  - travis_retry npm run test -- --watch=false
  - npm run e2e

after_success:
  - npm i -g angular-cli-ghpages
  - npm run build -- --prod --base-href "https://goshafighten.github.io/dx-ngx-application/"
  - angular-cli-ghpages

notifications:
  email:
    on_failure: always
    on_success: change
