language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - npm install -g @angular/cli
  - export CHROME_BIN=google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ng test --watch false
  - ng serve &
  - ng e2e

notifications:
  email:
    on_failure: always
    on_success: change