dist: trusty
sudo: false

language: node_js
node_js:
  - "6"

branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache: yarn

script:
  # Use Chromium instead of Chrome.
  - export CHROME_BIN=chromium-browser
  - npm run lint
  - travis_retry xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
  - xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js

after_success:
  - test $TRAVIS_BRANCH = "master" &&
    yarn global add angular-cli-ghpages &&
    npm run build -- --prod --base-href "https://goshafighten.github.io/dx-ngx-application/" &&
    angular-cli-ghpages

notifications:
  email:
    on_failure: always
    on_success: change
    